### PR TITLE
Fix one more keyword argument warning

### PR DESCRIPTION
**Pull request by tmatilai**
At least one more warning escaped #248.

### CODE REVIEW

**Comment by tmatilai** [comment]
> This change leaves the test suite with no warnings.

Yes, unfortunately that method does not have tests...

**Comment by olleolleolle** [comment]
Is it possible to add a test, in this PR?

**Comment by tmatilai** [comment]
Hmm, what would you like it to test? Anyway, I think it has been something like 10 years since I used Minitest last time, so would take me some time to study how to mock things etc.

**Comment by leejarvis** [comment]
Thanks @tmatilai -- I don't actually receive any warnings _before_ this change when running the test suite. Should I?

**Comment by leejarvis** [comment]
Oh sorry I misunderstood the last command. There's no coverage so the tests don't show a warning. Don't worry about adding a test, I can do that. Happy to merge this @olleolleolle

**Comment by olleolleolle** [comment]
Thanks, everyone! Glad that we got good outcomes!

**Comment by ankane** [comment]
Just fyi to other users: you can use `$VERBOSE = nil` to disable this warning until a new version is released.

**Comment by leejarvis** [comment]
I can see that getting annoying so I've released [4.8.1](https://rubygems.org/gems/slop/versions/4.8.1). Thanks for the bump, @ankane

**Comment by ankane** [comment]
Even better, thanks @leejarvis

**Pull request merged**
