### PR TITLE
Fix arguments removed with option arguments

### PR DESCRIPTION
**Pull request by NigoroJr**
Related to #181. Let me know if further changes are needed :ear:

### CODE REVIEW

**Comment by leejarvis** [comment]
Nice one, thanks!

I'm wondering, though; might it be better to use `each_with_index` on the pairs and follow each flag/argument with its paired index? This might be more accurate than using the flag value to extract the index, since presumably it gets ambiguous when you have multiple flags. What do you think?

**Comment by NigoroJr** [comment]
The reason I did the weird slicing thing was because I was worried about the odd case where there's something between the flag and the argument (like `--foo something actual_arg`), which now that I think about it, is ridiculous.

I think it's safe to assume there is no such thing, and you're right about using `each_with_index` (and it's not the "Ruby way" to play odd tricks with the array indexes). Are you thinking about something along the line of:

```ruby
arguments.each_with_index do |arg, i|
  arguments.delete_at(i + 1) if arg == flag
end
```

?

**Comment by leejarvis** [comment]
Cool, thanks for the explanation.

> Are you thinking about something along the line of:
[snip]

Actually, I was thinking that we could track the flag index (and thus the argument index) inside the `pairs.each_with_index` block. i.e after the check for `flag == '--'`. Though I'm not actually sure that'll work, since presumably the indexes will change when other flags/arguments are removed from the array. 

Perhaps the flag and arg should be tracked inside a hash with they original flag index as the key, and then if the flag is used, we can just delete them from this hash. Maybe I'm over thinking this though..

**Comment by leejarvis** [comment]
Ah I think I misread your code, so maybe that will work fine. Happy for you to give that a try against the specs

**Comment by NigoroJr** [comment]
Okay, I think I got it working now. I tried going down the `pairs.each_with_index` route, but noticed that you can't tell the actual index in `arguments` just from the index in `pairs`.

**Comment by leejarvis** [comment]
Great, thanks for the work!

**Comment by NigoroJr** [comment]
Thanks!

**Pull request merged**
